# (c) Copyright 2023 Hewlett Packard Enterprise Development LP

name: Rust Checks

on:
  pull_request:

jobs:
  build:
    name: Rust Checks
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - name: Rust Format
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy
      - name: Test
        run: cargo test --verbose
