# (c) Copyright 2023 Hewlett Packard Enterprise Development LP

name: Rust Checks

on:
  pull_request:

jobs:
  build:
    name: Rust Checks
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Rust Format
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy
      - name: Test
        run: cargo test --verbose
