# (c) Copyright 2023 Hewlett Packard Enterprise Development LP

name: Rust Checks

on:
  pull_request:

jobs:
  build:
    name: Rust Checks
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
      - name: Rust Format
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy
      - name: Test
        run: cargo test --verbose
